#lang sicp
(define (make-queue)
  (let ((front-ptr '())
        (rear-ptr '()))
    (define (empty-queue?)
      (null? front-ptr))
    (define (front-queue)
      (if (empty-queue?)
          (error "FRONT called with an empty queue")
          (car front-ptr)))
    (define (insert-queue! item)
      (let ((new-rear (list item)))
        (cond ((empty-queue?)
               (set! front-ptr new-rear)
               (set! rear-ptr new-rear))
              (else
               (set-cdr! rear-ptr new-rear)
               (set! rear-ptr new-rear)))))
    (define (delete-queue!)
      (cond ((empty-queue?)
             (error "DELETE! called with an empty queue"))
            (else
             (set! front-ptr (cdr front-ptr)))))
    (define (print-queue)
      (display front-ptr)
      (newline))
    (define (dispatch m)
      (cond ((eq? m 'empty-queue?) empty-queue?)
            ((eq? m 'front-queue) front-queue)
            ((eq? m 'insert-queue!) insert-queue!)
            ((eq? m 'delete-queue!) delete-queue!)
            ((eq? m 'print-queue) print-queue)))
    dispatch))

(define q1 (make-queue))
((q1 'print-queue))(newline)
((q1 'insert-queue!) 'a)
((q1 'print-queue))(newline)
((q1 'insert-queue!) 'b)
((q1 'print-queue))(newline)
((q1 'insert-queue!) 'c)
((q1 'print-queue))(newline)
((q1 'delete-queue!))
((q1 'print-queue))(newline)
((q1 'delete-queue!))
((q1 'print-queue))(newline)
((q1 'delete-queue!))
((q1 'print-queue))(newline)
    